---
roles:
  - name: robertdebock.bootstrap
    version: 7.1.5
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.docker
    version: 7.6.0
  - name: xanmanning.k3s
    version: v3.6.1
  - name: r_pufky.pihole
    version: 3.0.4
  - name: l3d.unbound
    version: v1.1.0
collections:
  - name: community.general
    version: 13.3.0
  - name: community.library_inventory_filtering_v1
    version: 1.1.5
  - name: containers.podman
    version: 1.20.2
