---
all:
  children:
    os_managed:
      hosts:
        nuc4:
    podman:
      hosts:
        nuc4:
    semaphore:
      hosts:
        nuc4:
    reverse_proxy:
      hosts:
        nuc4:
    tls_issuer:
      hosts:
        nuc4:
