---
all:
  children:
    servers:
      hosts:
        p1:
        p2:
        p3:
        p4:

    pihole:
      hosts:
        p1:

    ansible:
      hosts:
        "127.0.0.1":
          ansible_connection: local
