---
all:
  children:
    k3s_cluster:
      vars:
        k3s_registration_address: "192.168.90.98"
      children:
        k3s_server:
          hosts:
            "192.168.90.3":
            "192.168.90.4":
            "192.168.90.5":

    ansible:
      hosts:
        "127.0.0.1":
          ansible_connection: local
