tls_automation_namespace: ENC[AES256_GCM,data:CYMQJKvvGor2eedLtx37OqOc3qdAjg==,iv:EwuLSqAGrv1XPBaAbL/qDb1arNclKhnuzWmBOAm6ay8=,tag:TBFHlX/YQdDrihwm4dm/gg==,type:str]
tls_automation_email: ENC[AES256_GCM,data:QhN2mkYbGYNZVLqB/HKm0DxOzdSCkPs/WOBe,iv:9BiwnSx+FHPboCoKKMNQc9pg/KlI/0O3uX4z8Ct4sos=,tag:GNxr4FXEFBGz2qPNVU2plw==,type:str]
tls_automation_timer_enabled: ENC[AES256_GCM,data:an6DQA==,iv:GcKl8Y4VaPxzPZkYC3PKU5h008NIvK9Z3JqP2swiN5M=,tag:tH8QhUIxbj+SppFgd1UXnQ==,type:bool]
tls_automation_cloudflare_token: ENC[AES256_GCM,data:GqjLrY/hXXxB3pf/OXDdJ/QXn41ErR817tDke+QjD1Wq3kS9izLG6mvrvjbqVz8TzpOSKcU=,iv:UO61HPiy1Bof19wSq4pdtTDqeHz2MssNvrKan+2MPHg=,tag:tBk35CAkUW3jHc2ehFNrNg==,type:str]
reverse_proxy_bind_addresses:
    - ENC[AES256_GCM,data:NCKfVKicXQQNz3mvcg==,iv:fUKm1yeO4unnNYNbw1r6IUinMAeK5t2mrqgIwzEcGaA=,tag:mOgh0XsDKQZtI/mIzfvPag==,type:str]
reverse_proxy_client_sources:
    - ENC[AES256_GCM,data:HRxRfL6awKXIJaYuQZNY,iv:v9NIrBswPePBQizIeCyYbJXv+2Gx1mu4oC64Ny7yMxg=,tag:yW25ZzNVGtuCSes/Q8guiw==,type:str]
reverse_proxy_routes:
    - hostname: ENC[AES256_GCM,data:77hLEs0A1q15LdgOLZvzQpg7XnuQRAX/h2mMXlqiJ/pL,iv:sd/6Qb4DC1Vj4v+mT4ZYsrnAHc7XlyZ+IUfFGrfsoPk=,tag:G4fHPmyYNHygcRqmURc5rg==,type:str]
      certificate_name: ENC[AES256_GCM,data:0LE02QI=,iv:dYYpIZ90lMJPWRET/HH47MoewZN6xpxjLkCC9DYjqes=,tag:ThHUa3S5GPndBABOp6yYjA==,type:str]
      backend:
        transport: ENC[AES256_GCM,data:NmEcGQ==,iv:+yUj54SJOF0J7MBI6Xpzlqvw/j7YYAfARp5di4LFBZ4=,tag:Ii1zSXlIuBgScjwtKojfoQ==,type:str]
        address: ENC[AES256_GCM,data:Zh7pBpRzun+g7doK,iv:40Q7uRaLOx1z3Q7FmYGbE115M3oEd9XEczxhTI7pzH8=,tag:+Mh4EZSEUVwwLUe9dU8ErA==,type:str]
        port: ENC[AES256_GCM,data:DOU=,iv:kdfdP34nZzDClSPQJz5TjRB6OcHxxKU00cJfcHShhgQ=,tag:WKt6P3Un6/qB/ZPhq2aiuw==,type:int]
    - hostname: ENC[AES256_GCM,data:SVS6cav0aTK3xG6/Q3q1zc/e+o1f+5zIjEJ2ZDDd474=,iv:Mmkhoh5rU05H8lZRqz1/j9m21c/Wk0VATW3iRfnR7kI=,tag:UXVSsAe+nlIw2sW+Is3hQg==,type:str]
      certificate_name: ENC[AES256_GCM,data:0LE02QI=,iv:dYYpIZ90lMJPWRET/HH47MoewZN6xpxjLkCC9DYjqes=,tag:ThHUa3S5GPndBABOp6yYjA==,type:str]
      backend_port: ENC[AES256_GCM,data:kbM9OYM=,iv:yeOCG1p0NkqI2idQkakaSWqfl5D17fVlN7CkfKWRQNE=,tag:hoh59asMDkVCpsizxUECnA==,type:int]
semaphore_database_password: ENC[AES256_GCM,data:NFFrKiHxpvxDRI4+ffKrlvL8XFMpX4m2DeqvL6mRiD26U3zQOAd1aA==,iv:wkeXL0XBCqLsvXe0JsXAYo2jcr965dojRyQ9vBNpLCI=,tag:lhRFTJdQX1CKfw6RJp5Cxg==,type:str]
semaphore_admin_login: ENC[AES256_GCM,data:kuAVe8c=,iv:uR8Ri00FktXYXZvI6Uw0Y66sJsdztV637pNQ+5++1nk=,tag:J8ziuS+2RQvLFVSxQqfxhA==,type:str]
semaphore_admin_password: ENC[AES256_GCM,data:AUbGpQdtUxRuX+fBGvadLXXtU6Z/obH89B7oiPOGTMNMLre1i/txow==,iv:WJKShEhn6LCpekSVDztVTQksnZZuTcGpz7L9B9gm4Rg=,tag:B8XHfaHIddZMbbrhFg21pA==,type:str]
semaphore_admin_name: ENC[AES256_GCM,data:FpPogufTp+N36bCXXg==,iv:R2GVdMSXUvfVzdvVMorziQKaeQfY++yj64cUV4caQLI=,tag:D3BqWcTOe+fNUq/6bjVwRg==,type:str]
semaphore_admin_email: ENC[AES256_GCM,data:tlyKMMQUULXnWEviXVEn8AiKFhUeHIDZvONz5ehQLm75XQ==,iv:3HVmOxcTht38IRGS8jPIo+wSLeE9mR3aEPatvzqK14I=,tag:GucvDXPm2uq+WWqCHajdXQ==,type:str]
semaphore_cookie_hash: ENC[AES256_GCM,data:NFQ4yh1blr2HEGOqVzgDMzgwWK8Z9jkatkCzoWJsgh4mZsbTPM3GJPXdznE=,iv:EpsWjBlt+ehz03p+ZKLOuPJ6myNBn2rGEALfDJePJ94=,tag:uqPk3Vu/Gr6hMXScaske3g==,type:str]
semaphore_cookie_encryption: ENC[AES256_GCM,data:eRNSnuFbiocfX1lc9NnWrlHzEfpKqDV70bDXNxSjv3ZY5FSH9Ipo22WP+Ak=,iv:gcOgqdTnlFeEW0wBqAPSwSPmqDz0wojgftMhlAP6OmM=,tag:TEpDWd4m2nppQnfpp69b0w==,type:str]
semaphore_access_key_encryption: ENC[AES256_GCM,data:qnYe+nTxt7NljaXlACnwQicSgor5D7XVBbpZrOYkQXrlWSZeXZ0cI5VlvPg=,iv:3STfWlbp3Tmius5T3FuQdr7fi67DusJNDDHCf96pG48=,tag:wvLpMJEVcxBE5yxFjitDNw==,type:str]
semaphore_rclone_config: ENC[AES256_GCM,data:rjsxV6A/YY/VfH1NxSffF/Pu0pXhkh8CW/2zEzAkHVxiMs4oOMOOCzHmDydd5NgiIp7iKJbVw6Foy8W/bqg4dd8WuxvhmaM3x9LXxS2Q79xi,iv:e3EXU5nO8Dcq2yNRURP+6Tiuy71gNJb9fmnsQLi+NDo=,tag:8cTJDp4VUxh0lTsid289vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjBsc1BQZ3Z6TjBnTC9j
            SElYcmhuTTlPd2J6YVhheEZNTDM1dFRla0UwCmNxejZPTG0raDNONnZiZWJtV0NF
            VVFVdHZuYS9maVd2UFJZVjdMbk5iWE0KLS0tIDR1cm1XbVI3T0R2M1Y2VVdVU09q
            U2tCMzZxamUrbnVCa3g0d1Znd2lvWnMKCHjnJKnHSF3mm0XJPLa7QOje8lu1H9f1
            8wqovM3Rw4OWOigodeC+vjeSU40Z2YPDTljfOGKwKfr0xKPi4K0WSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehm0ehd2v2emfuycf2p0suhg94ej29zcu96ffmh3t6afchhjd99sxc4984
    encrypted_regex: ^(.*)$
    lastmodified: "2026-09-13T00:43:07Z"
    mac: ENC[AES256_GCM,data:9j5r0fPgVE2wdsRckzY6uHTWnAaqX7HivWLKv9EemWXwXBmcWF2hfhqe8BIZuy1qRTDKRe2YIbeF8z6/uF6UoseAa4A/sVroch9DY9LCdNhZbqhU7hDqCSr4gJuxEyyS6/fgknbIv1F7vIQn7b7KRZ9gWNqQjNCmK1zhD3ywNa8=,iv:1HF/ecIImbCpx7Tc1Nd/ZRLn0Vs1YwMlKbrB6Vitifc=,tag:6fgiYYTxPluO8TJm2xC9Tw==,type:str]
    version: 3.13.2
