tls_automation_namespace: ENC[AES256_GCM,data:CYMQJKvvGor2eedLtx37OqOc3qdAjg==,iv:EwuLSqAGrv1XPBaAbL/qDb1arNclKhnuzWmBOAm6ay8=,tag:TBFHlX/YQdDrihwm4dm/gg==,type:str]
tls_automation_email: ENC[AES256_GCM,data:QhN2mkYbGYNZVLqB/HKm0DxOzdSCkPs/WOBe,iv:9BiwnSx+FHPboCoKKMNQc9pg/KlI/0O3uX4z8Ct4sos=,tag:GNxr4FXEFBGz2qPNVU2plw==,type:str]
tls_automation_timer_enabled: ENC[AES256_GCM,data:an6DQA==,iv:GcKl8Y4VaPxzPZkYC3PKU5h008NIvK9Z3JqP2swiN5M=,tag:tH8QhUIxbj+SppFgd1UXnQ==,type:bool]
tls_automation_cloudflare_token: ENC[AES256_GCM,data:GqjLrY/hXXxB3pf/OXDdJ/QXn41ErR817tDke+QjD1Wq3kS9izLG6mvrvjbqVz8TzpOSKcU=,iv:UO61HPiy1Bof19wSq4pdtTDqeHz2MssNvrKan+2MPHg=,tag:tBk35CAkUW3jHc2ehFNrNg==,type:str]
reverse_proxy_bind_addresses:
    - ENC[AES256_GCM,data:NCKfVKicXQQNz3mvcg==,iv:fUKm1yeO4unnNYNbw1r6IUinMAeK5t2mrqgIwzEcGaA=,tag:mOgh0XsDKQZtI/mIzfvPag==,type:str]
reverse_proxy_client_sources:
    - ENC[AES256_GCM,data:HRxRfL6awKXIJaYuQZNY,iv:v9NIrBswPePBQizIeCyYbJXv+2Gx1mu4oC64Ny7yMxg=,tag:yW25ZzNVGtuCSes/Q8guiw==,type:str]
reverse_proxy_routes:
    - hostname: ENC[AES256_GCM,data:77hLEs0A1q15LdgOLZvzQpg7XnuQRAX/h2mMXlqiJ/pL,iv:sd/6Qb4DC1Vj4v+mT4ZYsrnAHc7XlyZ+IUfFGrfsoPk=,tag:G4fHPmyYNHygcRqmURc5rg==,type:str]
      certificate_name: ENC[AES256_GCM,data:0LE02QI=,iv:dYYpIZ90lMJPWRET/HH47MoewZN6xpxjLkCC9DYjqes=,tag:ThHUa3S5GPndBABOp6yYjA==,type:str]
      backend:
        transport: ENC[AES256_GCM,data:NmEcGQ==,iv:+yUj54SJOF0J7MBI6Xpzlqvw/j7YYAfARp5di4LFBZ4=,tag:Ii1zSXlIuBgScjwtKojfoQ==,type:str]
        address: ENC[AES256_GCM,data:Zh7pBpRzun+g7doK,iv:40Q7uRaLOx1z3Q7FmYGbE115M3oEd9XEczxhTI7pzH8=,tag:+Mh4EZSEUVwwLUe9dU8ErA==,type:str]
        port: ENC[AES256_GCM,data:DOU=,iv:kdfdP34nZzDClSPQJz5TjRB6OcHxxKU00cJfcHShhgQ=,tag:WKt6P3Un6/qB/ZPhq2aiuw==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjBsc1BQZ3Z6TjBnTC9j
            SElYcmhuTTlPd2J6YVhheEZNTDM1dFRla0UwCmNxejZPTG0raDNONnZiZWJtV0NF
            VVFVdHZuYS9maVd2UFJZVjdMbk5iWE0KLS0tIDR1cm1XbVI3T0R2M1Y2VVdVU09q
            U2tCMzZxamUrbnVCa3g0d1Znd2lvWnMKCHjnJKnHSF3mm0XJPLa7QOje8lu1H9f1
            8wqovM3Rw4OWOigodeC+vjeSU40Z2YPDTljfOGKwKfr0xKPi4K0WSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehm0ehd2v2emfuycf2p0suhg94ej29zcu96ffmh3t6afchhjd99sxc4984
    encrypted_regex: ^(.*)$
    lastmodified: "2026-09-10T23:47:42Z"
    mac: ENC[AES256_GCM,data:gUe1v0nBngT96A6DcFOsCnvxd/rr3FvivD8yttmg625/6B9+L8op229Gb7ggrAUGeF7Thc5hpdMFK/DFf95F4LZeex2s1gC4uHrs2qYehr+Yttxlg9SFMw3jCrQMb1u/DB/vsGjEoq2cW3XCWXpfyIjlGPlnLP9Ht3p3cXrLHOM=,iv:736LfGe2Xh5A5co3iCJ38MVAQ3gH88FujjI0mnSqRNw=,tag:kFyUYr8HLvdY59DH+VIcIA==,type:str]
    version: 3.13.2
