---
pihole_pihole_dns_1: 127.0.0.1#5335
pihole_dnsmasq_listening: single
unbound_listen_addresses:
  - '127.0.0.1@5335'
  - '::1@5335'
pihole_dns_list_file: /etc/pihole/custom.list

pihole_dns_records:
  - 192.168.90.101 traefik.lab.supermorphic.com
  - 192.168.90.101 longhorn.lab.supermorphic.com
  - 192.168.90.101 grafana.lab.supermorphic.com
  - 192.168.90.101 prometheus.lab.supermorphic.com
  - 192.168.90.101 homepage.lab.supermorphic.com
  - 192.168.90.101 uptime-kuma.lab.supermorphic.com
  - 192.168.90.101 gatus.lab.supermorphic.com
  - 192.168.90.102 traefik.staging.lab.supermorphic.com
  - 192.168.90.102 longhorn.staging.lab.supermorphic.com
  - 192.168.90.102 grafana.staging.lab.supermorphic.com
  - 192.168.90.102 prometheus.staging.lab.supermorphic.com
  - 192.168.90.102 homepage.staging.lab.supermorphic.com
  - 192.168.90.102 uptime-kuma.staging.lab.supermorphic.com
  - 192.168.90.102 gatus.staging.lab.supermorphic.com

pihole_dns_cname_records: []
