---
- name: Install Debian AppArmor packages
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles
    state: present
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Enable and start Debian AppArmor
  ansible.builtin.systemd_service:
    name: apparmor
    enabled: true
    state: started
  when:
    - ansible_facts['os_family'] == 'Debian'
    - security_baseline_apply_kernel_controls | bool
