---
- name: Assert the host uses the supported operating system family
  ansible.builtin.assert:
    that:
    - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: >-
      system-maintenance does not support operating-system family
      received {{ ansible_os_family }}

- name: Include setup tasks for the operating system family
  ansible.builtin.include_tasks: 'setup-{{ ansible_os_family }}.yml'
