---
- name: Install package-management utilities
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
    update_cache: true
    lock_timeout: "{{ system_maintenance_package_lock_timeout }}"

- name: Fully update installed packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
    lock_timeout: "{{ system_maintenance_package_lock_timeout }}"
  tags:
    - molecule-idempotence-notest

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
    state: absent
    lock_timeout: "{{ system_maintenance_package_lock_timeout }}"
